version: '3.8'

services: 
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fine-system
    ports:
      - 3306:3306
    volumes: 
      
      - db-data:/var/lib/mysql
      

volumes: 
  
  db-data: